// astro.config.mjs

import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// Import paths for sidebars that will be generated by your Node.js script.
// Ensure these paths match where your script will output the sidebar files.
// For example, if your script generates 'astro.sidebar.en.ts' and 'astro.sidebar.ja.ts' in the root.
import enSidebar from './astro.sidebar.en'; // Will be generated for English content
// import jaSidebar from './astro.sidebar.ja'; // Uncomment when Japanese content and sidebar are ready

export default defineConfig({

	routing: {
		prefixDefaultLocale: true
	},
	integrations: [
		starlight({
			// General site title (can be overridden per locale if needed, but often set in default language)
			title: 'My Awesome Documentation',
			sidebar: enSidebar,  // Assign the imported English sidebar

			// Define the locales (languages) your site supports.
			locales: {
				// English configuration
				en: {
					label: 'English',    // Label for the language picker
					lang: 'en',          // HTML lang attribute value
				},
				// Japanese configuration
				ja: {
					label: '日本語',     // Label for the language picker (Japanese)
					lang: 'ja',          // HTML lang attribute value
					// sidebar: jaSidebar, // Assign the imported Japanese sidebar (uncomment when ready)
					// If Japanese UI strings are significantly different or need custom overrides,
					// Starlight will also look for translations in `src/content/i18n/ja.json`.
				},
				// You can add more languages here in the future.
			},
			// Set English as the default language for the site.
			defaultLocale: 'en',

			// Optional: Add other global Starlight configurations here, for example:
			// social: {
			//   github: 'https://github.com/your-org/your-repo',
			// },
			// editLink: {
			//   baseUrl: 'https://github.com/your-org/your-repo/edit/main/',
			// },
		}),
	],
});